version: "3.7"

services:
  api:
    image: wishlist-dev:latest
    build:
      context: ./config
      target: "develop"
      args:
        INSTALL_JUPYTER: "true"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./config:/webapps
    env_file:
      - .env.defaults
      - .env
    environment:
      # inside container use: $JUPYTER
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
    ports:
      - 8000:8000
      - 8888:8888 # jupyterlab

  db:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.defaults
      - .env

volumes:
  postgres_data_dev:
    driver: local
